site_name: WiiPiiDo Documentation
repo_url: https://github.com/globaltronic/wiipiido-docs
theme: readthedocs

markdown_extensions:
    - admonition

nav:
  - 'Home': index.md
  - 'Getting Started': getting-started.md
