site_name: WiiPiiDo Documentation
repo_url: https://github.com/globaltronic/wiipiido-docs
theme:
  name: 'material'
  logo: 'https://github.com/Globaltronic/wiipiido-docs/raw/master/docs/img/WIIPIIDO_LOGO.ico'
  favicon: 'https://github.com/Globaltronic/wiipiido-docs/raw/master/docs/img/WIIPIIDO_LOGO.ico'
  palette:
    primary: 'blue'
    accent: 'light blue'

markdown_extensions:
    - admonition
    - codehilite
    - pymdownx.inlinehilite
    - pymdownx.superfences

plugins:
  - search
  - autolinks
  - git-revision-date-localized:
      type: datetime
  - minify:
      minify_html: true

extra:
  social:
    - type: 'home'
      link: 'http://www.globaltronic.pt/en/'
    - type: 'github'
      link: 'https://github.com/globaltronic'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/globaltronic-electronics-and-telecommunications/'

nav:
  - 'Home': index.md
  - 'Getting Started': getting-started.md
  - 'Armbian': armbian.md
  - 'Yocto': yocto.md
  # - 'Peripherals Examples': peripheral-examples.md
